- name: Create masters directory
  file:
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
    path: "{{ dns_config_directory }}/master"

- name: Create logging directory
  file:
    state: directory
    owner: "{{ dns_user }}"
    group: "{{ dns_user }}"
    mode: 0755
    path: "{{ dns_log_directory }}"

- name: Get serial
  script:
    cmd: files/get_dns_serial.sh
  register: dns_serial_raw

- name: Set serial
  set_fact:
    dns_serial: "{{ dns_serial_raw.stdout }}"

- name: Configure logging
  copy:
    src: logging
    dest: "{{ dns_config_directory }}/named.conf.logging"
    owner: "root"
    group: "root"
    mode: 0644
  notify: Restart dns

- name: Configure main
  template:
    owner: "root"
    group: "root"
    mode: 0644
    src: main
    dest: "{{ dns_config_directory }}/named.conf"
  notify: Restart dns

- name: Configure options
  template:
    owner: "root"
    group: "root"
    mode: 0644
    src: options
    dest: "{{ dns_config_directory }}/named.conf.options"
  notify: Restart dns

- name: Configure acl
  template:
    owner: "root"
    group: "root"
    mode: 0644
    src: acl
    dest: "{{ dns_config_directory }}/named.conf.acl"
  notify: Restart dns

- name: Configure blacklist
  template:
    owner: "root"
    group: "root"
    mode: 0644
    src: blacklist
    dest: "{{ dns_config_directory }}/named.conf.blacklist"
  notify: Restart dns

- name: Configure default-zones
  template:
    owner: "root"
    group: "root"
    mode: 0644
    src: default_zones
    dest: "{{ dns_config_directory }}/named.conf.default-zones"
  notify: Restart dns

- name: Configure zones
  template:
    owner: "root"
    group: "root"
    mode: 0644
    src: zones
    dest: "{{ dns_config_directory }}/named.conf.zones"
  notify: Restart dns

- name: Generate zone host files
  template:
    owner: "root"
    group: "root"
    mode: 0644
    src: zone_hosts
    dest: "{{ dns_config_directory }}/master/{{ item.name }}.hosts"
  with_items: "{{ dns_zones.masters + dns_blackilist }}"
  notify: Restart dns

# - name: Bail!
#   fail:
#     msg: "Don't apply config."

- name: Allow DNS
  ufw:
    port: 53
    rule: allow
