---
- name: Start dns
  service:
    name: "{{ dns_service }}"
    state: started
    enabled: yes

- name: Restart dns
  service:
    name: "{{ dns_service }}"
    state: restarted
    enabled: yes

- name: Reload dns
  service:
    name: "{{ dns_service }}"
    state: reloaded
    enabled: yes
